apiVersion: v1
kind: Service
metadata:
  name: test-server-service
spec:
  type: LoadBalancer
  ports:
  - port: 8443
  selector:
    app: test-server

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: test-server-service
# spec:
#   type: NodePort
#   selector:
#     app: test-server
#   ports:
#     - protocol: TCP
#       port: 8443
