apiVersion : apps/v1
kind: Deployment
metadata:
  name: zishaneapiproject 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zishaneapiproject
  template:
    metadata:
      labels:
        app: zishaneapiproject 
    spec:
      containers:
        - name: zishaneapiproject 
          image: tgbotreg.azurecr.io/zishaneapiproject
          ports:
          - containerPort: 3000